In [2]:
import numpy as np

In [5]:
x,y = np.arange(0,6).reshape(3,2),  np.arange(7,11).reshape(2,2)
x,y

(array([[0, 1],
        [2, 3],
        [4, 5]]),
 array([[ 7,  8],
        [ 9, 10]]))

In [6]:
np.random.seed(55)
a=np.random.randint(5,10,(5,3))
a
# a.ndim

array([[7, 5, 8],
       [6, 5, 8],
       [9, 5, 6],
       [5, 8, 7],
       [8, 5, 8]])

In [7]:
a1=a.flatten()
a1

array([7, 5, 8, 6, 5, 8, 9, 5, 6, 5, 8, 7, 8, 5, 8])

In [15]:
a1un,a1cnt=np.unique((a1),return_counts=True)
print(a1un,'\n',"counts","\n", a1cnt )                 #new line is giving me error # clear# showing /n n next line

[5 6 7 8 9] 
 counts 
 [5 2 2 5 1]


In [17]:
print(a1)
l=list(a1)

# g=[l[i]=a1.count(i) for i in a]
    
# print(g)

# for i in a1un:
#     for a1 in a1cnt:
#         print(i,a1)

# g= {i:l.count(i) for i in l}   # another way of doing it
# g
    
# list(zip(a1un,a1cnt))

# {i:j for i,j in zip(a1un,a1cnt)}

dict(zip(a1un,a1cnt))   #best way to do it

[7 5 8 6 5 8 9 5 6 5 8 7 8 5 8]


{5: 5, 6: 2, 7: 2, 8: 5, 9: 1}

In [74]:
a1.argmax()

6

In [76]:
print(a1)
np.where(a1%2!=0,-1,a1)

[7 5 8 6 5 8 9 5 6 5 8 7 8 5 8]


array([-1, -1,  8,  6, -1,  8, -1, -1,  6, -1,  8, -1,  8, -1,  8])